var obfield = require('./obfield.js');
var unfield = {
	'UNIT_FIELD_CHARM': obfield.OBJECT_END + 0x0000, // Size: 2, Type: LONG, Flags: PUBLIC
	'UNIT_FIELD_SUMMON': obfield.OBJECT_END + 0x0002, // Size: 2, Type: LONG, Flags: PUBLIC
	'UNIT_FIELD_CRITTER': obfield.OBJECT_END + 0x0004, // Size: 2, Type: LONG, Flags: PRIVATE
	'UNIT_FIELD_CHARMEDBY': obfield.OBJECT_END + 0x0006, // Size: 2, Type: LONG, Flags: PUBLIC
	'UNIT_FIELD_SUMMONEDBY': obfield.OBJECT_END + 0x0008, // Size: 2, Type: LONG, Flags: PUBLIC
	'UNIT_FIELD_CREATEDBY': obfield.OBJECT_END + 0x000A, // Size: 2, Type: LONG, Flags: PUBLIC
	'UNIT_FIELD_TARGET': obfield.OBJECT_END + 0x000C, // Size: 2, Type: LONG, Flags: PUBLIC
	'UNIT_FIELD_CHANNEL_OBJECT': obfield.OBJECT_END + 0x000E, // Size: 2, Type: LONG, Flags: PUBLIC
	'UNIT_CHANNEL_SPELL': obfield.OBJECT_END + 0x0010, // Size: 1, Type: INT, Flags: PUBLIC
	'UNIT_FIELD_BYTES_0': obfield.OBJECT_END + 0x0011, // Size: 1, Type: BYTES, Flags: PUBLIC
	'UNIT_FIELD_HEALTH': obfield.OBJECT_END + 0x0012, // Size: 1, Type: INT, Flags: PUBLIC
	'UNIT_FIELD_POWER1': obfield.OBJECT_END + 0x0013, // Size: 1, Type: INT, Flags: PUBLIC
	'UNIT_FIELD_POWER2': obfield.OBJECT_END + 0x0014, // Size: 1, Type: INT, Flags: PUBLIC
	'UNIT_FIELD_POWER3': obfield.OBJECT_END + 0x0015, // Size: 1, Type: INT, Flags: PUBLIC
	'UNIT_FIELD_POWER4': obfield.OBJECT_END + 0x0016, // Size: 1, Type: INT, Flags: PUBLIC
	'UNIT_FIELD_POWER5': obfield.OBJECT_END + 0x0017, // Size: 1, Type: INT, Flags: PUBLIC
	'UNIT_FIELD_POWER6': obfield.OBJECT_END + 0x0018, // Size: 1, Type: INT, Flags: PUBLIC
	'UNIT_FIELD_POWER7': obfield.OBJECT_END + 0x0019, // Size: 1, Type: INT, Flags: PUBLIC
	'UNIT_FIELD_MAXHEALTH': obfield.OBJECT_END + 0x001A, // Size: 1, Type: INT, Flags: PUBLIC
	'UNIT_FIELD_MAXPOWER1': obfield.OBJECT_END + 0x001B, // Size: 1, Type: INT, Flags: PUBLIC
	'UNIT_FIELD_MAXPOWER2': obfield.OBJECT_END + 0x001C, // Size: 1, Type: INT, Flags: PUBLIC
	'UNIT_FIELD_MAXPOWER3': obfield.OBJECT_END + 0x001D, // Size: 1, Type: INT, Flags: PUBLIC
	'UNIT_FIELD_MAXPOWER4': obfield.OBJECT_END + 0x001E, // Size: 1, Type: INT, Flags: PUBLIC
	'UNIT_FIELD_MAXPOWER5': obfield.OBJECT_END + 0x001F, // Size: 1, Type: INT, Flags: PUBLIC
	'UNIT_FIELD_MAXPOWER6': obfield.OBJECT_END + 0x0020, // Size: 1, Type: INT, Flags: PUBLIC
	'UNIT_FIELD_MAXPOWER7': obfield.OBJECT_END + 0x0021, // Size: 1, Type: INT, Flags: PUBLIC
	'UNIT_FIELD_POWER_REGEN_FLAT_MODIFIER': obfield.OBJECT_END + 0x0022, // Size: 7, Type: FLOAT, Flags: PRIVATE, OWNER
	'UNIT_FIELD_POWER_REGEN_INTERRUPTED_FLAT_MODIFIER': obfield.OBJECT_END + 0x0029, // Size: 7, Type: FLOAT, Flags: PRIVATE, OWNER
	'UNIT_FIELD_LEVEL': obfield.OBJECT_END + 0x0030, // Size: 1, Type: INT, Flags: PUBLIC
	'UNIT_FIELD_FACTIONTEMPLATE': obfield.OBJECT_END + 0x0031, // Size: 1, Type: INT, Flags: PUBLIC
	'UNIT_VIRTUAL_ITEM_SLOT_ID': obfield.OBJECT_END + 0x0032, // Size: 3, Type: INT, Flags: PUBLIC
	'UNIT_FIELD_FLAGS': obfield.OBJECT_END + 0x0035, // Size: 1, Type: INT, Flags: PUBLIC
	'UNIT_FIELD_FLAGS_2': obfield.OBJECT_END + 0x0036, // Size: 1, Type: INT, Flags: PUBLIC
	'UNIT_FIELD_AURASTATE': obfield.OBJECT_END + 0x0037, // Size: 1, Type: INT, Flags: PUBLIC
	'UNIT_FIELD_BASEATTACKTIME': obfield.OBJECT_END + 0x0038, // Size: 2, Type: INT, Flags: PUBLIC
	'UNIT_FIELD_RANGEDATTACKTIME': obfield.OBJECT_END + 0x003A, // Size: 1, Type: INT, Flags: PRIVATE
	'UNIT_FIELD_BOUNDINGRADIUS': obfield.OBJECT_END + 0x003B, // Size: 1, Type: FLOAT, Flags: PUBLIC
	'UNIT_FIELD_COMBATREACH': obfield.OBJECT_END + 0x003C, // Size: 1, Type: FLOAT, Flags: PUBLIC
	'UNIT_FIELD_DISPLAYID': obfield.OBJECT_END + 0x003D, // Size: 1, Type: INT, Flags: PUBLIC
	'UNIT_FIELD_NATIVEDISPLAYID': obfield.OBJECT_END + 0x003E, // Size: 1, Type: INT, Flags: PUBLIC
	'UNIT_FIELD_MOUNTDISPLAYID': obfield.OBJECT_END + 0x003F, // Size: 1, Type: INT, Flags: PUBLIC
	'UNIT_FIELD_MINDAMAGE': obfield.OBJECT_END + 0x0040, // Size: 1, Type: FLOAT, Flags: PRIVATE, OWNER, PARTY_LEADER
	'UNIT_FIELD_MAXDAMAGE': obfield.OBJECT_END + 0x0041, // Size: 1, Type: FLOAT, Flags: PRIVATE, OWNER, PARTY_LEADER
	'UNIT_FIELD_MINOFFHANDDAMAGE': obfield.OBJECT_END + 0x0042, // Size: 1, Type: FLOAT, Flags: PRIVATE, OWNER, PARTY_LEADER
	'UNIT_FIELD_MAXOFFHANDDAMAGE': obfield.OBJECT_END + 0x0043, // Size: 1, Type: FLOAT, Flags: PRIVATE, OWNER, PARTY_LEADER
	'UNIT_FIELD_BYTES_1': obfield.OBJECT_END + 0x0044, // Size: 1, Type: BYTES, Flags: PUBLIC
	'UNIT_FIELD_PETNUMBER': obfield.OBJECT_END + 0x0045, // Size: 1, Type: INT, Flags: PUBLIC
	'UNIT_FIELD_PET_NAME_TIMESTAMP':obfield.OBJECT_END + 0x0046, // Size: 1, Type: INT, Flags: PUBLIC
	'UNIT_FIELD_PETEXPERIENCE': obfield.OBJECT_END + 0x0047, // Size: 1, Type: INT, Flags: OWNER
	'UNIT_FIELD_PETNEXTLEVELEXP': obfield.OBJECT_END + 0x0048, // Size: 1, Type: INT, Flags: OWNER
	'UNIT_DYNAMIC_FLAGS': obfield.OBJECT_END + 0x0049, // Size: 1, Type: INT, Flags: DYNAMIC
	'UNIT_MOD_CAST_SPEED': obfield.OBJECT_END + 0x004A, // Size: 1, Type: FLOAT, Flags: PUBLIC
	'UNIT_CREATED_BY_SPELL': obfield.OBJECT_END + 0x004B, // Size: 1, Type: INT, Flags: PUBLIC
	'UNIT_NPC_FLAGS': obfield.OBJECT_END + 0x004C, // Size: 1, Type: INT, Flags: DYNAMIC
	'UNIT_NPC_EMOTESTATE': obfield.OBJECT_END + 0x004D, // Size: 1, Type: INT, Flags: PUBLIC
	'UNIT_FIELD_STAT0': obfield.OBJECT_END + 0x004E, // Size: 1, Type: INT, Flags: PRIVATE, OWNER
	'UNIT_FIELD_STAT1': obfield.OBJECT_END + 0x004F, // Size: 1, Type: INT, Flags: PRIVATE, OWNER
	'UNIT_FIELD_STAT2': obfield.OBJECT_END + 0x0050, // Size: 1, Type: INT, Flags: PRIVATE, OWNER
	'UNIT_FIELD_STAT3': obfield.OBJECT_END + 0x0051, // Size: 1, Type: INT, Flags: PRIVATE, OWNER
	'UNIT_FIELD_STAT4': obfield.OBJECT_END + 0x0052, // Size: 1, Type: INT, Flags: PRIVATE, OWNER
	'UNIT_FIELD_POSSTAT0': obfield.OBJECT_END + 0x0053, // Size: 1, Type: INT, Flags: PRIVATE, OWNER
	'UNIT_FIELD_POSSTAT1': obfield.OBJECT_END + 0x0054, // Size: 1, Type: INT, Flags: PRIVATE, OWNER
	'UNIT_FIELD_POSSTAT2': obfield.OBJECT_END + 0x0055, // Size: 1, Type: INT, Flags: PRIVATE, OWNER
	'UNIT_FIELD_POSSTAT3': obfield.OBJECT_END + 0x0056, // Size: 1, Type: INT, Flags: PRIVATE, OWNER
	'UNIT_FIELD_POSSTAT4': obfield.OBJECT_END + 0x0057, // Size: 1, Type: INT, Flags: PRIVATE, OWNER
	'UNIT_FIELD_NEGSTAT0': obfield.OBJECT_END + 0x0058, // Size: 1, Type: INT, Flags: PRIVATE, OWNER
	'UNIT_FIELD_NEGSTAT1': obfield.OBJECT_END + 0x0059, // Size: 1, Type: INT, Flags: PRIVATE, OWNER
	'UNIT_FIELD_NEGSTAT2': obfield.OBJECT_END + 0x005A, // Size: 1, Type: INT, Flags: PRIVATE, OWNER
	'UNIT_FIELD_NEGSTAT3': obfield.OBJECT_END + 0x005B, // Size: 1, Type: INT, Flags: PRIVATE, OWNER
	'UNIT_FIELD_NEGSTAT4': obfield.OBJECT_END + 0x005C, // Size: 1, Type: INT, Flags: PRIVATE, OWNER
	'UNIT_FIELD_RESISTANCES': obfield.OBJECT_END + 0x005D, // Size: 7, Type: INT, Flags: PRIVATE, OWNER, PARTY_LEADER
	'UNIT_FIELD_RESISTANCEBUFFMODSPOSITIVE': obfield.OBJECT_END + 0x0064, // Size: 7, Type: INT, Flags: PRIVATE, OWNER
	'UNIT_FIELD_RESISTANCEBUFFMODSNEGATIVE': obfield.OBJECT_END + 0x006B, // Size: 7, Type: INT, Flags: PRIVATE, OWNER
	'UNIT_FIELD_BASE_MANA': obfield.OBJECT_END + 0x0072, // Size: 1, Type: INT, Flags: PUBLIC
	'UNIT_FIELD_BASE_HEALTH': obfield.OBJECT_END + 0x0073, // Size: 1, Type: INT, Flags: PRIVATE, OWNER
	'UNIT_FIELD_BYTES_2': obfield.OBJECT_END + 0x0074, // Size: 1, Type: BYTES, Flags: PUBLIC
	'UNIT_FIELD_ATTACK_POWER': obfield.OBJECT_END + 0x0075, // Size: 1, Type: INT, Flags: PRIVATE, OWNER
	'UNIT_FIELD_ATTACK_POWER_MODS': obfield.OBJECT_END + 0x0076, // Size: 1, Type: TWO_SHORT, Flags: PRIVATE, OWNER
	'UNIT_FIELD_ATTACK_POWER_MULTIPLIER': obfield.OBJECT_END + 0x0077, // Size: 1, Type: FLOAT, Flags: PRIVATE, OWNER
	'UNIT_FIELD_RANGED_ATTACK_POWER': obfield.OBJECT_END + 0x0078, // Size: 1, Type: INT, Flags: PRIVATE, OWNER
	'UNIT_FIELD_RANGED_ATTACK_POWER_MODS': obfield.OBJECT_END + 0x0079, // Size: 1, Type: TWO_SHORT, Flags: PRIVATE, OWNER
	'UNIT_FIELD_RANGED_ATTACK_POWER_MULTIPLIER': obfield.OBJECT_END + 0x007A, // Size: 1, Type: FLOAT, Flags: PRIVATE, OWNER
	'UNIT_FIELD_MINRANGEDDAMAGE': obfield.OBJECT_END + 0x007B, // Size: 1, Type: FLOAT, Flags: PRIVATE, OWNER
	'UNIT_FIELD_MAXRANGEDDAMAGE': obfield.OBJECT_END + 0x007C, // Size: 1, Type: FLOAT, Flags: PRIVATE, OWNER
	'UNIT_FIELD_POWER_COST_MODIFIER': obfield.OBJECT_END + 0x007D, // Size: 7, Type: INT, Flags: PRIVATE, OWNER
	'UNIT_FIELD_POWER_COST_MULTIPLIER': obfield.OBJECT_END + 0x0084, // Size: 7, Type: FLOAT, Flags: PRIVATE, OWNER
	'UNIT_FIELD_MAXHEALTHMODIFIER': obfield.OBJECT_END + 0x008B, // Size: 1, Type: FLOAT, Flags: PRIVATE, OWNER
	'UNIT_FIELD_HOVERHEIGHT': obfield.OBJECT_END + 0x008C, // Size: 1, Type: FLOAT, Flags: PUBLIC
	'UNIT_FIELD_PADDING': obfield.OBJECT_END + 0x008D, // Size: 1, Type: INT, Flags: NONE
	'UNIT_END': obfield.OBJECT_END + 0x008E,
};
module.exports = unfield;